# Perfil WProton para: COTTOn.RockWithYou.ORIENTAL.NIGHT.DREAMS-GoldBerg  (editable a mano o via ./wproton.sh --config)
GAMEID="umu-default"
STORE="none"
RUNNER="wine-11.13-staging-tkg-amd64-wow64"
EXE_OVERRIDE="game.exe"
ARGS_OVERRIDE=""
PREFIX_MODE="shared"
MANGOHUD=0
PAD_SDL=auto
PAD_STEAMFIX=1
NESTED_GAMESCOPE=0
NTSYNC=0
FAVORITO=0
NOTAS="Necesita WineTKG11.13"
PLAY_COUNT=5
PLAY_SECONDS=528
LAST_PLAYED="2026-08-08 09:04"
SAVE_PATHS="/home/dani/Descargas/DeckStation/Apps/wproton/prefixes/default/drive_c/users/dani/AppData/Roaming/GSE Saves/3079970:/home/dani/Descargas/DeckStation/Apps/wproton/prefixes/default/drive_c/users/steamuser/AppData/Roaming/GSE Saves/3079970"
USE_BATOCERA=0
GAMEMODE=1
FSYNC=0
ESYNC=0
DXVK_ASYNC=1
WAYLAND=0
WINED3D=0
FSR=0
LAA=0
GAMESCOPE=""
DLL_OVERRIDES=""
GAME_LANG=""
EXTRA_ENV=""
