# Perfil WProton para: Demeo_x_Dungeons_and_Dragons_Battlemarked  (editable a mano o via ./wproton.sh --config)
GAMEID="umu-default"
STORE="none"
RUNNER="GE-Proton11-3"
EXE_OVERRIDE=""
ARGS_OVERRIDE="-nonvr"
PREFIX_MODE="shared"
MANGOHUD=0
PAD_SDL=auto
PAD_STEAMFIX=1
NESTED_GAMESCOPE=0
NTSYNC=0
FAVORITO=0
NOTAS=""
PLAY_COUNT=1
PLAY_SECONDS=146
LAST_PLAYED="2026-08-08 10:56"
SAVE_PATHS="/home/dani/Descargas/DeckStation/Apps/wproton/prefixes/default/drive_c/users/dani/AppData/Local/dxvk:/home/dani/Descargas/DeckStation/Apps/wproton/prefixes/default/drive_c/users/dani/AppData/LocalLow/Resolution Games/Battlemarked:/home/dani/Descargas/DeckStation/Apps/wproton/prefixes/default/drive_c/users/steamuser/AppData/Local/dxvk:/home/dani/Descargas/DeckStation/Apps/wproton/prefixes/default/drive_c/users/steamuser/AppData/LocalLow/Resolution Games/Battlemarked"
USE_BATOCERA=0
GAMEMODE=1
FSYNC=1
ESYNC=1
DXVK_ASYNC=1
WAYLAND=0
WINED3D=0
FSR=0
LAA=0
GAMESCOPE=""
DLL_OVERRIDES=""
GAME_LANG=""
EXTRA_ENV=""
