# Perfil WProton para: Dragon_Ball_Fighter_Z_Legendary_Edition  (editable a mano o via ./wproton.sh --config)
GAMEID="umu-default"
STORE="none"
RUNNER="ge-custom"
EXE_OVERRIDE="drive_c/Games/DRAGON BALL FighterZ Legendary Edition/RED/Binaries/Win64/DRAGON_BALL_FighterZ.exe"
ARGS_OVERRIDE=""
PREFIX_MODE="bundled"
MANGOHUD=0
PAD_SDL=1
USE_BATOCERA=0
GAMEMODE=1
FSYNC=1
ESYNC=1
DXVK_ASYNC=1
WAYLAND=0
WINED3D=0
FSR=0
LAA=0
GAMESCOPE=""
DLL_OVERRIDES=""
GAME_LANG=""
EXTRA_ENV=""
