# Perfil WProton para: Need_for_Speed_Underground_2_Remastered  (editable a mano o via ./wproton.sh --config)
GAMEID="umu-default"
STORE="none"
RUNNER=""
EXE_OVERRIDE="drive_c/Games/Need for Speed Underground 2 Remastered/SPEED2.EXE"
ARGS_OVERRIDE=""
PREFIX_MODE="own"
MANGOHUD=0
PAD_SDL=auto
PAD_SONY=auto
KEYS_ESTILO=xbox
PAD_STEAMFIX=0
NESTED_GAMESCOPE=0
NTSYNC=0
FAVORITO=0
COMPLETADO=0
NOTAS=""
PLAY_COUNT=0
PLAY_SECONDS=0
SAVE_PATHS=""
USE_BATOCERA=0
GAMEMODE=1
FSYNC=1
ESYNC=1
DXVK_ASYNC=1
WAYLAND=0
HDR=0
WINED3D=0
FSR=0
LAA=0
GAMESCOPE=""
DLL_OVERRIDES="dinput8=n,b"
GAME_LANG=""
EXTRA_ENV=""
